name: twinned_widgets
description: "Widget library for Boodskap IoT Digital Twin Platform"
version: 1.0.0
homepage: https://twinned.digital

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  twin_commons:
    git:
      url: https://github.com/boodskap/twin_commons.git
      ref: main
#    path:
#      twin_commons

  country_pickers: ^3.0.1
  data_table_2: ^2.5.10
  syncfusion_flutter_datagrid: ^25.2.6
  syncfusion_flutter_gauges: ^25.2.6
  syncfusion_flutter_sliders: ^25.2.7
  search_choices: ^2.2.7
  accordion: ^2.6.0
  toggle_switch: ^2.3.0
  percent_indicator: ^4.2.3
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
 
  select2dot1: ^2.0.9
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true

analyzer:
  errors:
    invalid_annotation_target: ignore